sen1=input("enter the first sentence")
sen2=input("enter the second sentence")
split1=sen1.split()
split2=sen2.split()
set1=set(split1)
set2=set(split2)
I=set1.intersection(set2)
U=set1.union(set2)
length1=len(I)
length2=len(U)
print((length1)/(length2))
